import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="flex-none w-full bg-gray-100 text-gray-800">
          <div className="mx-auto py-4 px-4 sm:px-6 lg:px-8">
            <p className="text-center text-sm text-gray-500 hover:text-gray-700">
              <a 
                href="https://janharkonen.fi" 
                target="_blank" 
                rel="noopener noreferrer"
                className="hover:bg-gray-200"
                >
                © Jan Härkönen 2025
              </a>
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
